function G = combineModels(GList, Const)
GList = updateGraph(GList, Const);
nGraph = length(GList);
nAllNode = GList(end).param.nAllNode;
nAllEdge = GList(end).param.nAllEdge;
nAllTime = GList(end).param.nAllTime;
iNodeEnd = nAllNode;
iEdgeEnd = nAllEdge;
iTimeEnd = nAllTime;
nBus = GList(1).param.nBus;
nodes = [];
edges = [];
chargeType = [];
nChargers = zeros([nGraph,1]);
nSoc = zeros([nGraph,1]);
nDSoc = zeros([nGraph,1]);
discharge = zeros([nBus,nGraph]);
varType = [];
upperBound = [];
lowerBound = [];
isOnPeak = [];
for iGraph = nGraph:-1:1
    nGraphNode = GList(iGraph).param.nNode;
    nGraphEdge = GList(iGraph).param.nEdge;    
    nGraphTime = GList(iGraph).param.fleetProfile.nTime;
    iNodeStart = iNodeEnd - nGraphNode + 1;
    iTimeStart = iTimeEnd - nGraphTime + 1;
    iEdgeStart = iEdgeEnd - nGraphEdge + 1;
    nodes(iNodeStart:iNodeEnd,:) = GList(iGraph).nodes;
    edges(iEdgeStart:iEdgeEnd,:) = GList(iGraph).edges;  
    chargeType(iTimeStart:iTimeEnd) = GList(iGraph).chargeType;
    iTimeEnd = iTimeStart - 1;
    iNodeEnd = iNodeStart - 1;
    iEdgeEnd = iEdgeStart - 1;    
    nChargers(iGraph) = GList(iGraph).param.nCharger;
    nSoc(iGraph) = GList(iGraph).param.fleetProfile.nSoc;
    nDSoc(iGraph) = GList(iGraph).param.fleetProfile.nCharge;
    discharge(:,iGraph) = GList(iGraph).param.fleetProfile.discharge;
    varType = [GList(iGraph).param.varType; varType]; %#ok
    upperBound = [GList(iGraph).param.upperBound; upperBound]; %#ok
    lowerBound = [GList(iGraph).param.lowerBound; lowerBound]; %#ok
    isOnPeak = [GList(iGraph).param.fleetProfile.isOnPeak isOnPeak]; %#ok
end
G.nodes = nodes;
G.edges = edges;
G.chargeType = chargeType;
G.param.base = GList(1).param.base;
G.param.nCharger = nChargers;
G.param.nEdge = nAllEdge;
G.param.nNode = nAllNode;
G.param.nSolution = sum(nSoc) + sum(nDSoc) + nAllEdge + 2;
G.param.nSoc = sum(nSoc);
G.param.nDSoc = sum(nDSoc);
G.param.soc = GList(1).param.fleetProfile.soc;
G.param.discharge = max(discharge,[],2);
G.param.nTime = nAllTime;
G.param.tStart = GList(1).param.tStart;
G.param.syncTime = GList(1).param.syncTime;
G.param.varType = varType;
G.param.upperBound = [upperBound; inf; inf];
G.param.lowerBound = [lowerBound; 0; 0];
G.param.isOnPeak = isOnPeak;
end
